### ISSUE TITLE
Añade tu testimonio

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/javascript-inspirate#1]
Hola Lector:

Si quieres que tu testimonio se publique en [la web del libro...](https://leanpub.com/javascript-inspirate)

Solo tienes que responder a este issue con un mensaje, el título del mismo es opcional.

**Muchas gracias!**

**Comment by jorgeroden** [comment]
Hola Ulises:

El ebook me parece que ofrece una muy buena perspectiva de Javascript dentro del ámbito de la tecnología web. Contiene información muy valiosa que continuará creciendo al ser un ebook "vivo" y colaborativo. Grande y generosa decisión. Gracias Ulises.

**Comment by UlisesGascon** [comment]
Muchas gracias @jorgeroden! Acabo de añadirlo :)

**Comment by NuriaHill** [comment]
Hola @UlisesGascon . Despues de un año  de no hacer nada he retomado con ganas la programación. Tu libro me parece un gran punto de partida teniendo en cuenta que mi background no es para nada infórmatico pero no importa porque según lo has escrito es para "todos los públicos". Una vez mas, gracias por acercar la programacion a todos  y difundir sin ánimo de lucro, y sobre todo gracias por inspirar !

**Comment by ErikGIovani** [comment]
Leanpub pide comprar una membresia de 19 dolares anuales para poder leer los libros gratis 😥
