### ISSUE TITLE
Errores Ortográficos/Sintaxis ( Capitulo 4 )

### ISSUE THREAD

**Issue by ymdx** [UlisesGascon/javascript-inspirate#11]
Posición 82 : En ( # JavaScirpt # ) todo puede ser comparado en términos booleanos.

Posición 133 : se ejecutan solo ( # cuando # ) cuando la condición se cumple.

Posición 153 : console.log(" ( # Nos # ) son del mismo tipo y por eso...

Posición 266 : propia ( ? de ¿ ) hacer estructuras condicionales.

Posición 270 : Si estas empezando con ( # JavaScirpt # ) 

Posición 325 : " ( # Tines # ) que esperar aún. Lo siento.");

**Comment by UlisesGascon** [comment]
@ymdx no me queda claro el error de Posición 266.

texto original:

```
El *operador ternario (?:)* nos ofrece una manera propia hacer estructuras condicionales.
```

**Comment by ymdx** [comment]
" una manera propia hacer estructuras condicionales " -->->->-> falta un nexo de unión entre propia y hacer.

Seria " una manera propia **de** hacer estructuras condicionales " no ?

**Comment by UlisesGascon** [comment]
hahah... totalmente correcto... 

Claramente tengo que tomar cafe antes de arrancar con github! :)
