### ISSUE TITLE
typo Pagina 80

### ISSUE THREAD

**Issue by antoniogarcia78** [UlisesGascon/javascript-inspirate#27]
En el codigo de ejemplo de defineProperties se usa value:true cuando value es el valor de la propiedad.
Esa linea creo que sobra. No da error porque a continuacion se sobreescribe

```
Object.defineProperties(miObjeto, {
 "propiedad1": {
 value: true,
 writable: true,
 value: "Propiedad1 original..."
 },

```

**Comment by UlisesGascon** [comment]
Gracias @antoniogarcia78! Apuntado para la siguiente release!
