### ISSUE TITLE
[idea] capitulos en markdown

### ISSUE THREAD

**Issue by xDae** [UlisesGascon/javascript-inspirate#3]
No sé si lo tienes previsto, pero estaria guay tener los capitulos en el mismo repo en formato markdown así es más facil que la gente pueda colaborar para agregar ejemplos, corregir typos o cualquier cosilla.

Aparte si estuviera en markdown podrias hacer una pagina estatica a partir de ellos para poder leerlo o echarle un ojo directamente online de manera más comoda

**Comment by UlisesGascon** [comment]
Hola @xDae! Gracias por compartir tu idea... en principio Leanpub tiene una opción para visualizar el libro en [formato web](https://leanpub.com/javascript-inspirate/read_full). Estoy trabajando en un script para hacer la conversión de Markua a Markdown y viceversa...

Tienes razón que así será más sencillo contribuir, en cuanto lo tenga listo... lo aplicaremos aquí ;-)
