### ISSUE TITLE
Pequeño error ortográfico

### ISSUE THREAD

**Issue by AlvaroRM88** [UlisesGascon/javascript-inspirate#37]
Hola!

En el capitulo 9, linea 15

> JavaScript este paradigma se hace de otra forma, gracias a *[**Protoype**]

Creo que le faltaría una 't' a Prototype.

Muchas gracias por el libro!

**Comment by faustogut** [comment]
Hola @adglow
La errata que indicas ya esta solucionada en la rama dev. Gracias!
Por otro lado, he buscado en el resto del libro la misma errata y la he encontrado también en el capítulo 10.
He creado Pull Request corrigiendo esa errata también.
Buen aporte!
