### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tecnicbravo** [UlisesGascon/javascript-inspirate#4]
Capítulo 2 línea 88 "pseu**s**ocódigo". Está tan cerca de la d :)

**Comment by UlisesGascon** [comment]
Gracias! Ya está añadido para la próxima release [#454f6dd50cd4b1f6c8dd9d66402a3ac3dda73138](https://github.com/UlisesGascon/javascript-inspirate/commit/454f6dd50cd4b1f6c8dd9d66402a3ac3dda73138)
