### ISSUE TITLE
Agradecimientos pendientes

### ISSUE THREAD

**Issue by KoolTheba** [UlisesGascon/javascript-inspirate#42]
Te voy añadiendo a la lista te agradecimientos a las personas que hayan abierto issues para mejorar el libro y hecho PRs ;) 

### Lista 
- [Teba Gomez](https://github.com/kooltheba)
- [Andrés `(@7vlr)`](https://twitter.com/7vlr)
- [Theba Gómez](https://twitter.com/KoolTheba)
- [Álvaro Ramírez](https://github.com/AlvaroRM88)
- [Fausto Gutiérrez](https://github.com/faustogut)
- [Ana Enríquez](https://github.com/ValKiriann)
- [Antonio Garcia Marin](https://github.com/antoniogarcia78)
- [Faustogut  `(@faustogut)`](https://github.com/faustogut)
- [Ana  `(@anakb)`](https://github.com/anakb)
- [Victor `(@victorze)`](https://github.com/victorze)
- [Queli Coto](https://github.com/nothnk)
- [Juan A. Macías](https://github.com/soyjuanmacias)

**Comment by UlisesGascon** [comment]
Gracias!
