### ISSUE TITLE
Errores Ortográficos ( Versión Kindle )

### ISSUE THREAD

**Issue by ymdx** [UlisesGascon/javascript-inspirate#5]
_Posición 124_: ( **# JavaScirpt #** ) , pero no iremos más allá.

_Posición 447_: Precisamente la innovación pasará a formar parte del ADN de nuevos tipos de empresas como las ( **# Stratups #** ).

_Posición 452_: En este capitulo hablaremos sobre como es la computación y que se espera de un ( **# desarrolladore #** ).

_Posición 526_: ( **# nombreUusario #** ) = "Pepe".

_Posición 528_: var ( **# nombreUusario #** ) = "Pepe".

_Posición 3034_: Conversión array ( **# require #** ) de ciertos conocimientos avanzados en el uso de prototype y this.

**Comment by UlisesGascon** [comment]
Muchas gracias @ymdx ! Ya está todo incluido en la próxima release.

**Commits:**
- [643522825cadff1ae200cebfa165134d9ecb14b0](https://github.com/UlisesGascon/javascript-inspirate/commit/643522825cadff1ae200cebfa165134d9ecb14b0)
- [f6fab15e577dac972f591c33e38ae3d93be4e829](https://github.com/UlisesGascon/javascript-inspirate/commit/f6fab15e577dac972f591c33e38ae3d93be4e829)
- [62cd89e9f3ea7f9b99dbca8947c0204d78cd1de9](https://github.com/UlisesGascon/javascript-inspirate/commit/62cd89e9f3ea7f9b99dbca8947c0204d78cd1de9)
- [5739d534001afc7c224d5376790b91a646f3b7dc](https://github.com/UlisesGascon/javascript-inspirate/commit/5739d534001afc7c224d5376790b91a646f3b7dc)
