### ISSUE TITLE
Error nombre método página 86 del pdf

### ISSUE THREAD

**Issue by jivelazquez** [UlisesGascon/javascript-inspirate#50]
Al método:

.lastIdexOf()

le falta una "n" debería ser:

lastIndexOf()

**Comment by UlisesGascon** [comment]
Muchas gracias @jivelazquez! Arreglado en [c73ea9f](https://github.com/UlisesGascon/javascript-inspirate/commit/c73ea9f52211017d0eeeec37330448c9d8c788f0)
